/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardsRouteRouteImport } from './routes/dashboards/route'
import { Route as DatasourcesRouteImport } from './routes/datasources'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IntegrationsRouteRouteImport } from './routes/integrations/route'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards/index'
import { Route as DashboardsIdRouteImport } from './routes/dashboards/$id'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations/index'
import { Route as IntegrationsSentryRouteImport } from './routes/integrations/sentry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRouteRoute = DashboardsRouteRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesRoute = DatasourcesRouteImport.update({
  id: '/datasources',
  path: '/datasources',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRouteRoute = IntegrationsRouteRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardsRouteRoute,
} as any)
const DashboardsIdRoute = DashboardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardsRouteRoute,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntegrationsRouteRoute,
} as any)
const IntegrationsSentryRoute = IntegrationsSentryRouteImport.update({
  id: '/sentry',
  path: '/sentry',
  getParentRoute: () => IntegrationsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboards': typeof DashboardsRouteRouteWithChildren
  '/integrations': typeof IntegrationsRouteRouteWithChildren
  '/datasources': typeof DatasourcesRoute
  '/debug': typeof DebugRoute
  '/explore': typeof ExploreRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/dashboards/$id': typeof DashboardsIdRoute
  '/integrations/sentry': typeof IntegrationsSentryRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datasources': typeof DatasourcesRoute
  '/debug': typeof DebugRoute
  '/explore': typeof ExploreRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/dashboards/$id': typeof DashboardsIdRoute
  '/integrations/sentry': typeof IntegrationsSentryRoute
  '/dashboards': typeof DashboardsIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboards': typeof DashboardsRouteRouteWithChildren
  '/integrations': typeof IntegrationsRouteRouteWithChildren
  '/datasources': typeof DatasourcesRoute
  '/debug': typeof DebugRoute
  '/explore': typeof ExploreRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/dashboards/$id': typeof DashboardsIdRoute
  '/integrations/sentry': typeof IntegrationsSentryRoute
  '/dashboards/': typeof DashboardsIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboards'
    | '/integrations'
    | '/datasources'
    | '/debug'
    | '/explore'
    | '/settings'
    | '/templates'
    | '/dashboards/$id'
    | '/integrations/sentry'
    | '/dashboards/'
    | '/integrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datasources'
    | '/debug'
    | '/explore'
    | '/settings'
    | '/templates'
    | '/dashboards/$id'
    | '/integrations/sentry'
    | '/dashboards'
    | '/integrations'
  id:
    | '__root__'
    | '/'
    | '/dashboards'
    | '/integrations'
    | '/datasources'
    | '/debug'
    | '/explore'
    | '/settings'
    | '/templates'
    | '/dashboards/$id'
    | '/integrations/sentry'
    | '/dashboards/'
    | '/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardsRouteRoute: typeof DashboardsRouteRouteWithChildren
  IntegrationsRouteRoute: typeof IntegrationsRouteRouteWithChildren
  DatasourcesRoute: typeof DatasourcesRoute
  DebugRoute: typeof DebugRoute
  ExploreRoute: typeof ExploreRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasources': {
      id: '/datasources'
      path: '/datasources'
      fullPath: '/datasources'
      preLoaderRoute: typeof DatasourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof DashboardsRouteRoute
    }
    '/dashboards/$id': {
      id: '/dashboards/$id'
      path: '/$id'
      fullPath: '/dashboards/$id'
      preLoaderRoute: typeof DashboardsIdRouteImport
      parentRoute: typeof DashboardsRouteRoute
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof IntegrationsRouteRoute
    }
    '/integrations/sentry': {
      id: '/integrations/sentry'
      path: '/sentry'
      fullPath: '/integrations/sentry'
      preLoaderRoute: typeof IntegrationsSentryRouteImport
      parentRoute: typeof IntegrationsRouteRoute
    }
  }
}

interface DashboardsRouteRouteChildren {
  DashboardsIdRoute: typeof DashboardsIdRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
}

const DashboardsRouteRouteChildren: DashboardsRouteRouteChildren = {
  DashboardsIdRoute: DashboardsIdRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
}

const DashboardsRouteRouteWithChildren = DashboardsRouteRoute._addFileChildren(
  DashboardsRouteRouteChildren,
)

interface IntegrationsRouteRouteChildren {
  IntegrationsSentryRoute: typeof IntegrationsSentryRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
}

const IntegrationsRouteRouteChildren: IntegrationsRouteRouteChildren = {
  IntegrationsSentryRoute: IntegrationsSentryRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
}

const IntegrationsRouteRouteWithChildren =
  IntegrationsRouteRoute._addFileChildren(IntegrationsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardsRouteRoute: DashboardsRouteRouteWithChildren,
  IntegrationsRouteRoute: IntegrationsRouteRouteWithChildren,
  DatasourcesRoute: DatasourcesRoute,
  DebugRoute: DebugRoute,
  ExploreRoute: ExploreRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
