/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatasourcesRouteImport } from './routes/datasources'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as DashboardsIndexRouteImport } from './routes/dashboards/index'
import { Route as DashboardsIdRouteImport } from './routes/dashboards/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasourcesRoute = DatasourcesRouteImport.update({
  id: '/datasources',
  path: '/datasources',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIndexRoute = DashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsIdRoute = DashboardsIdRouteImport.update({
  id: '/dashboards/$id',
  path: '/dashboards/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datasources': typeof DatasourcesRoute
  '/debug': typeof DebugRoute
  '/explore': typeof ExploreRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/dashboards/$id': typeof DashboardsIdRoute
  '/dashboards/': typeof DashboardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datasources': typeof DatasourcesRoute
  '/debug': typeof DebugRoute
  '/explore': typeof ExploreRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/dashboards/$id': typeof DashboardsIdRoute
  '/dashboards': typeof DashboardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datasources': typeof DatasourcesRoute
  '/debug': typeof DebugRoute
  '/explore': typeof ExploreRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/dashboards/$id': typeof DashboardsIdRoute
  '/dashboards/': typeof DashboardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datasources'
    | '/debug'
    | '/explore'
    | '/settings'
    | '/templates'
    | '/dashboards/$id'
    | '/dashboards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datasources'
    | '/debug'
    | '/explore'
    | '/settings'
    | '/templates'
    | '/dashboards/$id'
    | '/dashboards'
  id:
    | '__root__'
    | '/'
    | '/datasources'
    | '/debug'
    | '/explore'
    | '/settings'
    | '/templates'
    | '/dashboards/$id'
    | '/dashboards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasourcesRoute: typeof DatasourcesRoute
  DebugRoute: typeof DebugRoute
  ExploreRoute: typeof ExploreRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  DashboardsIdRoute: typeof DashboardsIdRoute
  DashboardsIndexRoute: typeof DashboardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasources': {
      id: '/datasources'
      path: '/datasources'
      fullPath: '/datasources'
      preLoaderRoute: typeof DatasourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/': {
      id: '/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof DashboardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/$id': {
      id: '/dashboards/$id'
      path: '/dashboards/$id'
      fullPath: '/dashboards/$id'
      preLoaderRoute: typeof DashboardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasourcesRoute: DatasourcesRoute,
  DebugRoute: DebugRoute,
  ExploreRoute: ExploreRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  DashboardsIdRoute: DashboardsIdRoute,
  DashboardsIndexRoute: DashboardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
